### ISSUE TITLE
Cannot find -lgcc

### ISSUE THREAD

**Issue by tictakk** [jbrandwood/liberis#13]
Hey there, looking into tinkering with some PC-FX game making. I am not very knowledgeable about compilers or the toolchain so I could be doing something very dumb. 

I have v810-gcc built, it's in my path and same with pcfxtools (I did build this after I was getting my error though). When I run make examples, it fails when trying to build the first example. Here's the output:

`c/v810-gcc//v810/lib/crt0.o hello.o -leris -lc -lsim -lgcc -o hello.elf -Map hello.map
v810-ld: cannot find -lgcc
make[2]: *** [../example.mk:41: hello.elf] Error 1
make[2]: Leaving directory '/home/laconic/projects/liberis/examples/hello'
make[1]: *** [Makefile:29: cd] Error 2
make[1]: Leaving directory '/home/laconic/projects/liberis/examples'
make: *** [Makefile:42: example_cds] Error 2
`

Someone previously raised an issue about the linker but I'm not sure what I'm supposed to do to fix it. Thanks.

**Comment by jbrandwood** [comment]
Thanks for reporting this! I just fixed the path in examples/example.mk
